import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'NFT Analytics Site',
  description: 'Generated by konpay.eth',
}

export default function RootLayout({ children }: { children: React.ReactNode}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <header className="bg-gray-800 text-white py-4 px-8">
          <nav className="container mx-auto flex items-center justify-between">
            <h1 className="text-2xl font-bold">NFT Analytics Site</h1>
            <ul className="flex space-x-4">
              <li>
                <Link href="/">
                  <div className="text-white">Home</div>
                </Link>
              </li>
              <li>
                <Link href="/about">
                  <div className="text-white">About</div>
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        <main>{children}</main>
        <footer className="bg-gray-200 py-4 px-8 mt-8">
          <div className="container mx-auto text-center text-gray-500">
            &copy; 2023 NFT Market. All rights reserved.
            <p className="mt-2">
              This site uses data provided by the <a href="https://opensea.io/" target="_blank" rel="noopener noreferrer" className="underline text-blue-600">OpenSea</a>
            </p>
          </div>
        </footer>
      </body>
    </html>
  )
}
